### ISSUE TITLE
Compiler warning about left shift

### ISSUE THREAD

**Issue by mpbraendli** [gfto/libtsfuncs#1]
Hi,

My compiler complained about a shift operation, and I believe the line 495 of descs.c needs a small change, as `<<` has a higher precedence than `&`:

Replacing

    lcn          = data[i+2] &~ 0xc0 << 8;          // 11xxxxxx

by

    lcn          = (data[i+2] & ~0xc0) << 8;                // 11xxxxxx

looks more like the original intent of the code line.

**Comment by lars18th** [comment]
Hi,

As this is already fixed at https://github.com/gfto/libtsfuncs/commit/f2456cb2f4a040d7218e5fa7f6bedaf11e4eab81,
please close this issue.
:smile:
