### ISSUE TITLE
Lack of DVB-T NIT public functions

### ISSUE THREAD

**Issue by lars18th** [gfto/libtsfuncs#4]
Hi,

In the current "tsfuncs.h" header file, only functions for DVB-C are available:

- ts_nit_add_frequency_list_descriptor_cable();
- ts_nit_add_cable_delivery_descriptor();

I suggest to add the corresponding:

- ts_nit_add_frequency_list_descriptor_terrestrial();
- ts_nit_add_terrestrial_delivery_descriptor();

Thank you!

**Comment by gfto** [comment]
The only functions that are added are the ones that are used by my other software. If you need something additional, please submit a patch. If you need a solution that already have all the DVB (and more) tables look at: https://github.com/gfto/bitstream-1
